version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf5_ukr_apache
        ports:
          - 8763:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf5_ukr
        depends_on:
          - php

    mysql:
        image: mysql:5.7
        container_name: sf5_ukr_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
            - ./mysql/my.cnf:/usr/local/etc/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ukrFull
            MYSQL_USER: root
            MYSQL_PASSWORD: root

    php:
        build: .docker/php
        container_name: sf5_ukr_php
        volumes:
          - .:/home/wwwroot/sf5_ukr
        depends_on:
          - mysql
        ports:
          - 7676:7676
        environment:
          DATABASE_URL: mysql://root:root@sf5_ukr_mysql/ireceipt

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf5_ukr_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8891:80
        links:
            - mysql

